# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore ROFit/ROFit.csproj
RUN dotnet publish ROFit/ROFit.csproj \
    -c Release \
    -o /publish \
    --no-self-contained
RUN find /publish -type f | sort

# Cache bust
ARG BUILDTIME=unknown

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
ARG BUILDTIME=unknown
RUN echo "Build time: $BUILDTIME"
WORKDIR /app
COPY --from=build /publish ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "ROFit.dll"]